### ISSUE TITLE
fix coverage task on circle ci

### ISSUE THREAD

**Issue by travi** [travi/travi.org-admin#90]
```
grunt mochacov:coverage
Running "mochacov:coverage" (mochacov) task
Warning: /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3872
            throw e;
            ^

Error: Line 5: Unexpected reserved word
    at throwError (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1156:21)
    at throwUnexpected (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1204:17)
    at parsePrimaryExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1567:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3504:61)
    at parsePostfixExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1703:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseUnaryExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1784:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseMultiplicativeExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1790:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseAdditiveExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1807:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseShiftExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1824:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseRelationalExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1845:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseEqualityExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1863:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseANDExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1880:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseXORExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1896:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseBitwiseORExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1912:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseLogicalANDExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1930:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseLogicalORExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1946:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseConditionalExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1966:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseAssignmentExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:1993:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseExpression (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2020:20)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseStatement (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:2783:16)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parseSourceElement (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3057:24)
    at parseSourceElements (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3095:29)
    at parseProgram (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3109:19)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3609:38
    at parse (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/esprima/esprima.js:3856:23)
    at module.exports (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/node_modules/falafel/index.js:32:15)
    at Object.__dirname.blanket._blanket.instrument (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/src/blanket.js:115:37)
    at Object.require.extensions..js (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/blanket/src/index.js:148:25)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ubuntu/travi.org-admin/test/unit/routeRendererTest.jsx:6:19)
    at Module._compile (module.js:434:26)
    at Object.require.extensions..jsx (/home/ubuntu/travi.org-admin/node_modules/jsx-require-extension/index.js:11:17)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:187:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:184:14)
    at Mocha.run (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/mocha/lib/mocha.js:405:31)
    at Object.<anonymous> (/home/ubuntu/travi.org-admin/node_modules/grunt-mocha-cov/node_modules/mocha/bin/_mocha:405:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3 Use --force to continue.

Aborted due to warnings.


Execution Time (2015-10-30 02:36:25 UTC)
loading tasks            106ms  ▇▇▇ 6%
loading grunt-mocha-cov  169ms  ▇▇▇▇ 9%
mochacov:coverage         1.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 85%

Total 1.8s grunt mochacov:coverage returned exit code 3
```

**Comment by travi** [comment]
resolving this requires https://github.com/alex-seville/blanket/pull/530 being merged and that update being pulled into https://github.com/mmoulton/grunt-mocha-cov/ for https://github.com/mmoulton/grunt-mocha-cov/issues/43

**Comment by travi** [comment]
```
grunt mochacov:coverage
Running "mochacov:coverage" (mochacov) task
[error] "2015-12-19T22:02:33.994Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2015-12-19T22:02:33.995Z"  'input: ' ''
Warning: Unable to parse LCov coverage data: undefined Use --force to continue.

Aborted due to warnings.
```
