### ISSUE TITLE
fix cucumber test analysis on circle ci

### ISSUE THREAD

**Issue by travi** [travi/travi.org-admin#91]
```
cucumber.js --format=json --tags=~@wip test/integration/features/ --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber
fs.js:844
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/tmp/circle-junit.xtECIEt/cucumber/tests.cucumber'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1438:21)
    at Object.expandPathWithRegexp (/home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:23:23)
    at /home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:9:39
    at Array.forEach (native)
    at Object.expandPathsWithRegexp (/home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/argument_parser/path_expander.js:8:11)
    at Object.expandPaths (/home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/argument_parser/feature_path_expander.js:6:38)
    at Object.getFeatureFilePaths (/home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/argument_parser.js:50:71)

at Object.getFeatureSources (/home/ubuntu/nvm/versions/node/v4.0.0/lib/node_modules/cucumber/lib/cucumber/cli/configuration.js:36:48) cucumber.js --format=json --tags=~@wip test/integration/features/ --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber returned exit code 1
```

**Comment by travi** [comment]
this does fail the same way locally

**Comment by travi** [comment]
Also:

>Hi Matt,
We noticed your test results aren't being parsewd correctly. Looking at tests.cucumber inhttps://circleci.com/gh/travi/travi.org-admin/147 , it looks like some unrelated log lines are being included:
```
matching GET https://api.travi.org:443/ to GET https://api.travi.org:443/DnPgr37R: false
matching GET https://api.travi.org:443/foo to GET https://api.travi.org:443/foo: true
matching GET https://api.travi.org:443/foo to GET https://api.travi.org:443/DnPgr37R: false
[
  {
    "id": "homepage",
    "name": "homepage",[...]
```
I think the issue is that you do 
cucumber.js --format=json --tags=~@wip test/integration/features/ > $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber
Using `--out` rather than the shell redirection, as in our docs (https://circleci.com/docs/test-metadata#cucumber) should fix the issue.
Hope that's helpful, and sorry we don't have better error-reporting for this!
